const hobbies: string[] = [
  "3D printing",
  "Acrobatics",
  "Acting",
  "Amateur radio",
  "Animation",
  "Aquascaping",
  "Astrology",
  "Astronomy",
  "Baking",
  "Baton twirling",
  "Blogging",
  "Building",
  "Board/tabletop games",
  "Book discussion clubs",
  "Book restoration",
  "Bowling",
  "Brazilian jiu-jitsu",
  "Breadmaking",
  "Bullet journaling",
  "Cabaret",
  "Calligraphy",
  "Candle making",
  "Candy making",
  "Car fixing & building",
  "Card games",
  "Cheesemaking",
  "Cleaning",
  "Clothesmaking",
  "Coffee roasting",
  "Collecting",
  "Coloring",
  "Computer programming",
  "Confectionery",
  "Cooking",
  "Cosplaying",
  "Couponing",
  "Craft",
  "Creative writing",
  "Crocheting",
  "Cross-stitch",
  "Crossword puzzles",
  "Cryptography",
  "Cue sports"
];

export default hobbies;
